Update for release-v1.7.7
decred/decred-binaries pull request #149
Opened 2023-04-10 14:40 UTC by alexlyp

2023-04-10 15:31 UTC, chappjc commented on release-notes.md
> +  pair.   You can find the full rundown of improvements to DEX for 0.6.0 [here](https://github.com/decred/dcrdex/blob/master/docs/release-notes/release-notes-0.6.0.md).
Merged that, so link works now.

2023-04-18 13:02 UTC, jrick approved these changes

2023-04-18 16:05 UTC, jrick requested changes
decrediton signature isn't valid

2023-04-18 16:25 UTC, jrick approved these changes

2023-04-18 17:03 UTC, merged